### PR TITLE
Back - Add Dockerfile for the API

### PR DESCRIPTION
**Pull request by mationorato**
### Overview
Dockerfile for the Elixir REST API. Based on [Deploying with Releases](https://hexdocs.pm/phoenix/releases.html#containers) for phoenix applications.

### Build and Run
To test this dockerfile you can run:
```
cd api
docker build -t aleo_wallet_api .
docker run -p 5000:4000 aleo_wallet_api
```
The server should be running now, try an endpoint if you want:
```
curl -X POST http://127.0.0.1:5000/account
```

### Notes

This Dockerfile clones and builds the [Aleo SDK](https://github.com/AleoHQ/aleo). This should be avoided in the future when the Aleo CLI is updated in [crates.io](https://crates.io/)

### CODE REVIEW

**Review by facundoolano — COMMENTED** [review]
This LGTM, I'll try it locally tomorrow and in the nomad cluster as soon as it's ready

**Comment by facundoolano** [comment]
Does this require some extra setup? the docker run command seems to hang on a clean install: 

```
docker run -p 5000:4000 aleo_wallet_api

17:08:30.356 [info]  Starting application...
```

**Comment by facundoolano** [comment]
Nevermind, it seems it actually is working, it's just silent
```
curl -X POST http://127.0.0.1:5000/account

{"address":"aleo10qvy9c3hvrgxcdkj9w235we85ncxa7emu7u5g6eztfp6c52t9vzqtznev3","private_key":"...","view_key":"..."}%
```

**Comment by mationorato** [comment]
Yes, I should add some messages to the promt

**Pull request merged**
